apiVersion: v1
kind: Service
metadata:
  name: pona-discord-application
  namespace: pona-discord-application
spec:
  selector:
    app: pona-discord-application
  ports:
    - protocol: TCP
      port: 3450
      targetPort: 3000
  type: LoadBalancer